name: face-recognition-env  # Name of the environment

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - cmake  # Required for dlib
  - dlib  # Prebuilt dlib version from conda-forge
  - face-recognition
  - pip
  - pip:
      - face-recognition
